# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Olive & Mango
url: http://oliveandmango.com
email: j_headley@icloud.com
description: A lifestyle blog on food, travel and overall well-being. Tips for those living in Trinidad and Tobago as well as Toronto, Canada.
twitter_username: oliveandmango
instagram_username: theoliveandmango
facebook_username: oliveandmango
pintrest_username: olive_mango


paginate: 5

# Collections
collections:
    recipes:
        output: true


# Default settings
defaults:
    -
        values:
            comments: true

# Build settings
markdown: kramdown
permalink: /:title

gems:
  - jekyll-sitemap
  - jekyll-paginate


# Prose Config for drafts

prose:
  rooturl: ''
  siteurl: 'http://oliveandmango.com'
  metadata:
     _posts/blog:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "title"
          element: "text"
          placeholder: "Enter title"
      - name: "date"
        field:
          label: "date"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          label: "author"
          element: "text"
          value: "Joanne"
      - name: "permalink"
        field:
          label: "permalink"
          element: "text"
          placeholder: "Enter permalink"
      - name: "image"
        field:
          label: "image"
          element: "text"
          placeholder: "Enter image path"
      - name: "categories"
        field:
          label: "categories"
          element: "text"
          placeholder: "Enter categories"
      - name: "tags"
        field:
          label: "tags"
          element: "text"
          placeholder: "Enter tags"
      - name: "excerpt"
        field:
          label: "excerpt"
          element: "text"
          placeholder: "Enter excerpt"

     _drafts:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "title"
          element: "text"
          placeholder: "Enter title"
      - name: "date"
        field:
          label: "date"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          label: "author"
          element: "text"
          value: "Joanne"
      - name: "permalink"
        field:
          label: "permalink"
          element: "text"
          placeholder: "Enter permalink"
      - name: "image"
        field:
          label: "image"
          element: "text"
          placeholder: "Enter image path"
      - name: "categories"
        field:
          label: "categories"
          element: "text"
          placeholder: "Enter categories"
      - name: "tags"
        field:
          label: "tags"
          element: "text"
          placeholder: "Enter tags"
      - name: "excerpt"
        field:
          label: "excerpt"
          element: "text"
          placeholder: "Enter excerpt"
