# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Olive & Mango
url: http://oliveandmango.com
email: j_headley@icloud.com
description: A lifestyle blog on food, travel and overall well-being. Tips for those living in Trinidad and Tobago as well as Toronto, Canada.
twitter_username: oliveandmango
instagram_username: theoliveandmango
facebook_username: oliveandmango
pintrest_username: olive_mango

#Default settings
defaults:
    -
        values:
            comments: true

# Build settings
markdown: kramdown
permalink: /:title

gems:
  - jekyll-sitemap
