baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Olive & Mango"
disqusShortname = "disqus_Ci8qqqEWpn"

[params]
<<<<<<< HEAD
  description = "A blog on great, delicious and easy to make food with a dash of travel and well-being"
=======
  description = "Inspiring ideas for delicious home cooking"
>>>>>>> bf744f4e70502f4f5f0f33ce76888c4a19f6e3a0

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 1
[[menu.main]]
  name = "Recipes"
  url  = "/blog"
  weight = 2
[[menu.main]]
  name = "About"
  url  = "/about"
  weight = 3

[permalinks]
  blog = "/:slug/"


# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
