baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Olive & Mango"
disqusShortname = "disqus_Ci8qqqEWpn"
enableRobotsTXT = true
canonifyURLs = true


[params]
  description = "Inspiring ideas for delicious home cooking."
   AuthorName = "Joanne"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 1
[[menu.main]]
  name = "Recipes"
  url  = "/blog"
  weight = 2
[[menu.main]]
  name = "Work with me"
  url  = "/work-with-me"
  weight = 3
[[menu.main]]
  name = "Workshops"
  url  = "/workshops"
  weight = 4
[[menu.main]]
  name = "About"
  url  = "/about"
  weight = 5

[permalinks]
  blog = "/:slug/"


# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
